FROM ghdl/ghdl:ubuntu20-llvm-10
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y yosys npm gtkwave scrot xvfb python3-pyvirtualdisplay python3-pip
RUN pip3 install --upgrade setuptools wheel # ubuntu 18.04 apparently doesnt have proper setuptools
RUN pip3 install pillow pyscreenshot path
RUN npm install -g netlistsvg

RUN apt-get install -y git tcl-dev pkg-config clang libreadline-dev bison flex
RUN apt-get remove -y --purge yosys*

RUN mkdir /yosys_source

RUN cd /yosys_source && git clone https://github.com/YosysHQ/yosys.git && cd yosys && make -j$(nproc) && make install
RUN cd /yosys_source && git clone https://github.com/ghdl/ghdl-yosys-plugin.git && cd ghdl-yosys-plugin && make -j$(nproc) && make install

RUN mkdir /tools

COPY container/vcd2png.py /tools/
COPY container/hdl2svg.sh /tools/

CMD [ "/bin/bash" ]
